id: P008016
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4648
  title: བོད་ཀྱི་ཡི་གེའི་སྤྱི་རྣམ་བློ་གསལ་འཇུག་ངོགས།
  author: ''
  volumes:
    7fc41a7caa094665ab60591cf8a2849f:
      image_group_id: I3CN4650
      title: ''
      volume_number: 1
      total_pages: 292
ebook_metadata:
  title: བོད་ཀྱི་ཡི་གེའི་སྤྱི་རྣམ་བློ་གསལ་འཇུག་ངོགས།
  author: ''
  sku: P008016
  cover: cover.jpg
  layers:
  - pagination
